import type { ResourceKey } from "./resource-config";
import { RESOURCE_META } from "./resource-config";
import {
  bookingStages,
  customerStatuses,
  enquiryStages,
  eventTypes,
  packageLevels,
  quoteStatuses,
  serviceStatuses,
  taskPriorities,
  taskStatuses,
  vendorStatuses,
  VENUE_SETTING,
  CHANGE_IMPLEMENTATION_STATUS,
  MEDIA_CONSENT,
} from "@/models/enums";

export type FieldDef = {
  name: string;
  label: string;
  type?: "text" | "email" | "number" | "date" | "textarea" | "select" | "relation";
  required?: boolean;
  options?: readonly string[];
  relation?: ResourceKey;
};

export const RESOURCE_FIELDS: Record<ResourceKey, FieldDef[]> = {
  customers: [
    { name: "fullName", label: "Full name", required: true },
    { name: "mobileWhatsApp", label: "Mobile / WhatsApp" },
    { name: "email", label: "Email", type: "email" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: customerStatuses,
      required: true,
    },
    { name: "billingAddress", label: "Billing address", type: "textarea" },
    { name: "cityArea", label: "City / area" },
    { name: "decisionMaker", label: "Decision maker" },
    { name: "backupContact", label: "Backup contact" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  enquiries: [
    {
      name: "customerId",
      label: "Customer",
      type: "relation",
      relation: "customers",
      required: true,
    },
    { name: "eventType", label: "Event type", type: "select", options: eventTypes },
    { name: "occasionTitle", label: "Occasion title" },
    { name: "preferredDate", label: "Preferred date", type: "date" },
    { name: "expectedGuests", label: "Expected guests", type: "number" },
    { name: "venueStatusOrName", label: "Venue" },
    { name: "targetBudget", label: "Target budget", type: "number" },
    { name: "packageLevel", label: "Package", type: "select", options: packageLevels },
    { name: "stage", label: "Status", type: "select", options: enquiryStages, required: true },
    { name: "conversationNotes", label: "Notes", type: "textarea" },
  ],
  "event-briefs": [
    { name: "enquiryId", label: "Enquiry", type: "relation", relation: "enquiries" },
    { name: "eventId", label: "Event", type: "relation", relation: "bookings" },
    { name: "themeVision", label: "Theme / vision", type: "textarea" },
    { name: "colours", label: "Colours" },
    { name: "mustHaveElements", label: "Must-haves", type: "textarea" },
    { name: "elementsToAvoid", label: "Exclusions", type: "textarea" },
    { name: "foodDietaryNeeds", label: "Dietary needs", type: "textarea" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  quotes: [
    { name: "customerId", label: "Customer", type: "relation", relation: "customers" },
    { name: "enquiryId", label: "Enquiry", type: "relation", relation: "enquiries" },
    { name: "issueDate", label: "Issue date", type: "date" },
    { name: "validUntil", label: "Valid until", type: "date" },
    { name: "status", label: "Status", type: "select", options: quoteStatuses, required: true },
    { name: "discount", label: "Discount (PKR)", type: "number" },
    { name: "taxAmount", label: "Tax amount (PKR)", type: "number" },
    {
      name: "bookingAdvancePercent",
      label: "Advance rate (0–1, e.g. 0.6)",
      type: "number",
    },
    { name: "scopeAndExclusions", label: "Scope & exclusions", type: "textarea" },
  ],
  services: [
    { name: "servicePackageName", label: "Package name", required: true },
    { name: "categoryLevel", label: "Category / level" },
    { name: "pricingUnit", label: "Pricing unit" },
    { name: "status", label: "Status", type: "select", options: serviceStatuses },
    { name: "includedScope", label: "Included scope", type: "textarea" },
    { name: "excludedOptionalItems", label: "Excluded items", type: "textarea" },
    { name: "pricingNotes", label: "Pricing notes", type: "textarea" },
  ],
  bookings: [
    { name: "customerId", label: "Customer", type: "relation", relation: "customers" },
    { name: "enquiryId", label: "Enquiry", type: "relation", relation: "enquiries" },
    { name: "eventTitle", label: "Event title", required: true },
    { name: "eventType", label: "Event type", type: "select", options: eventTypes },
    { name: "eventDate", label: "Event date", type: "date" },
    { name: "guestCount", label: "Guests", type: "number" },
    { name: "venueId", label: "Venue", type: "relation", relation: "venues" },
    {
      name: "acceptedQuoteId",
      label: "Accepted quote",
      type: "relation",
      relation: "quotes",
    },
    { name: "stage", label: "Stage", type: "select", options: bookingStages },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  tasks: [
    { name: "eventId", label: "Event", type: "relation", relation: "bookings" },
    { name: "phase", label: "Phase" },
    { name: "taskActivityCue", label: "Task", required: true, type: "textarea" },
    { name: "responsiblePerson", label: "Owner" },
    { name: "dueStartAt", label: "Due / start", type: "date" },
    { name: "status", label: "Status", type: "select", options: taskStatuses },
    { name: "priority", label: "Priority", type: "select", options: taskPriorities },
  ],
  changes: [
    {
      name: "eventId",
      label: "Event",
      type: "relation",
      relation: "bookings",
      required: true,
    },
    { name: "requestedChange", label: "Requested change", type: "textarea", required: true },
    { name: "feeChangeExclTax", label: "Fee change (excl. tax)", type: "number" },
    {
      name: "implementationStatus",
      label: "Status",
      type: "select",
      options: CHANGE_IMPLEMENTATION_STATUS,
      required: true,
    },
  ],
  feedback: [
    { name: "eventId", label: "Event", type: "relation", relation: "bookings" },
    { name: "overallRating", label: "Rating (1-5)", type: "number" },
    { name: "whatWorkedWell", label: "What worked well", type: "textarea" },
    { name: "whatToImproveOpenIssues", label: "Improvements / issues", type: "textarea" },
    {
      name: "mediaConsent",
      label: "Media consent",
      type: "select",
      options: MEDIA_CONSENT,
    },
  ],
  vendors: [
    { name: "businessName", label: "Business name", required: true },
    { name: "category", label: "Category" },
    { name: "authorizedContact", label: "Contact" },
    { name: "mobileWhatsApp", label: "Mobile / WhatsApp" },
    { name: "email", label: "Email", type: "email" },
    { name: "vendorStatus", label: "Status", type: "select", options: vendorStatuses },
    { name: "notesIssues", label: "Notes", type: "textarea" },
  ],
  "vendor-orders": [
    {
      name: "eventId",
      label: "Event",
      type: "relation",
      relation: "bookings",
      required: true,
    },
    {
      name: "vendorId",
      label: "Vendor",
      type: "relation",
      relation: "vendors",
      required: true,
    },
    { name: "scopeSpecification", label: "Scope", type: "textarea" },
    { name: "quantity", label: "Quantity", type: "number" },
    { name: "unitRate", label: "Unit rate", type: "number" },
    { name: "status", label: "Status" },
  ],
  venues: [
    { name: "venueName", label: "Name", required: true },
    { name: "areaCity", label: "Area" },
    { name: "venueManager", label: "Manager" },
    { name: "managerMobile", label: "Contact" },
    { name: "guestCapacity", label: "Capacity", type: "number" },
    { name: "addressMapLink", label: "Address / map link" },
    { name: "setting", label: "Setting", type: "select", options: VENUE_SETTING },
    { name: "indicativeRental", label: "Indicative rental", type: "number" },
    { name: "securityDeposit", label: "Security deposit", type: "number" },
    { name: "parkingAccessibility", label: "Parking / accessibility" },
    {
      name: "decorFlameRiggingRules",
      label: "Decor / flame / rigging rules",
      type: "textarea",
    },
    {
      name: "emergencyContactFirstAid",
      label: "Emergency contact / first aid",
    },
  ],
  inventory: [
    { name: "itemAssetName", label: "Item name", required: true },
    { name: "category", label: "Category" },
    { name: "quantityHeld", label: "Qty held", type: "number" },
    { name: "currentCondition", label: "Condition" },
    { name: "storageLocation", label: "Storage" },
  ],
  handovers: [
    {
      name: "eventId",
      label: "Event",
      type: "relation",
      relation: "bookings",
      required: true,
    },
    { name: "itemId", label: "Item", type: "relation", relation: "inventory" },
    { name: "quantityOut", label: "Qty out", type: "number" },
    { name: "conditionOut", label: "Condition out" },
  ],
  invoices: [
    {
      name: "eventId",
      label: "Event",
      type: "relation",
      relation: "bookings",
      required: true,
    },
    { name: "milestone", label: "Milestone" },
    { name: "issueDate", label: "Issue date", type: "date" },
    { name: "dueDate", label: "Due date", type: "date" },
    { name: "status", label: "Status" },
    { name: "amountBilledInclTax", label: "Amount incl. tax", type: "number" },
  ],
  payments: [
    { name: "eventId", label: "Event", type: "relation", relation: "bookings" },
    { name: "transactionDate", label: "Date", type: "date" },
    { name: "transactionType", label: "Type" },
    { name: "invoiceId", label: "Invoice", type: "relation", relation: "invoices" },
    { name: "poId", label: "PO", type: "relation", relation: "vendor-orders" },
    { name: "payerPayee", label: "Payer / payee" },
    { name: "method", label: "Method" },
    { name: "amount", label: "Amount", type: "number", required: true },
    { name: "clearance", label: "Clearance" },
  ],
  expenses: [
    { name: "eventId", label: "Event", type: "relation", relation: "bookings" },
    { name: "recordedOn", label: "Recorded on", type: "date" },
    { name: "description", label: "Description", required: true },
    { name: "actualAgreedCost", label: "Actual cost", type: "number" },
    { name: "category", label: "Category" },
  ],
  documents: [
    { name: "documentCheck", label: "Document / check", required: true },
    { name: "scope", label: "Scope" },
    { name: "eventId", label: "Event", type: "relation", relation: "bookings" },
    { name: "status", label: "Status" },
    { name: "responsiblePerson", label: "Responsible" },
    { name: "notesTemplateFilename", label: "Notes / filename", type: "textarea" },
  ],
  marketing: [
    { name: "platform", label: "Platform" },
    { name: "contentType", label: "Content type" },
    { name: "eventId", label: "Event", type: "relation", relation: "bookings" },
    { name: "postTopicCaption", label: "Caption / topic", type: "textarea" },
    { name: "status", label: "Status" },
    { name: "plannedPublishDate", label: "Planned date", type: "date" },
  ],
};

export const RESOURCE_LABELS = Object.fromEntries(
  Object.values(RESOURCE_META).map((m) => [
    m.key,
    { title: m.title, singular: m.singular, adminPath: m.adminPath },
  ]),
) as Record<ResourceKey, { title: string; singular: string; adminPath: string }>;
